{
  lib,
  fetchFromGitHub,
  fetchNpmDeps,
  rustPlatform,
  cargo-tauri,
  nodejs,
  npmHooks,
  pkg-config,
  wrapGAppsHook3,
  webkitgtk_4_1,
  gtk3,
  glib-networking,
  openssl,
  dbus,
  libayatana-appindicator,
  alsa-lib,
  gst_all_1,
  jq,
  moreutils,
  makeWrapper,
}:

rustPlatform.buildRustPackage (finalAttrs: {
  pname = "worldmonitor";
  version = "2.5.21";

  src = fetchFromGitHub {
    owner = "koala73";
    repo = "worldmonitor";
    tag = "v${finalAttrs.version}";
    hash = "sha256-qa3UGqeChtvGv3O9UjiVj9ObT8ZHb4gjvv8tSMs2G5E=";
  };

  cargoRoot = "src-tauri";
  buildAndTestSubdir = "src-tauri";

  cargoHash = "sha256-Uf8emebxCv8RUP3JdGXH0Ry+t8HSDBdvSsVSzxSODoA=";

  npmDeps = fetchNpmDeps {
    inherit (finalAttrs) pname version src;
    hash = "sha256-WnU+6QuIXy8osS9JW7Cc3NItOvzEz38bDILI/SY0Ii8=";
  };

  nativeBuildInputs = [
    cargo-tauri.hook
    nodejs
    npmHooks.npmConfigHook
    pkg-config
    wrapGAppsHook3
    jq
    moreutils
    makeWrapper
  ];

  buildInputs = [
    webkitgtk_4_1
    gtk3
    glib-networking
    openssl
    dbus
    libayatana-appindicator
    alsa-lib
    gst_all_1.gstreamer
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-bad
  ];

  env = {
    OPENSSL_NO_VENDOR = true;
    # Skip sharp's native libvips download (transitive dep, not needed for build)
    npm_config_sharp_install = "false";
  };

  npmFlags = [ "--ignore-scripts" ];

  postPatch = ''
    # Disable updater artifacts and remove beforeBuildCommand (we handle it ourselves)
    jq '.bundle.createUpdaterArtifacts = false | .build.beforeBuildCommand = ""' \
      src-tauri/tauri.conf.json | sponge src-tauri/tauri.conf.json

    # Remove upstream .cargo/config.toml which defines a vendored-sources entry
    # that conflicts with the one generated by buildRustPackage's cargoSetupHook
    rm -f src-tauri/.cargo/config.toml
  '';

  preBuild = ''
    # Build the sidecar sebuf bundle
    node scripts/build-sidecar-sebuf.mjs

    # Build the frontend
    npx tsc
    npx vite build
  '';

  postInstall = ''
    wrapProgram $out/bin/world-monitor \
      --prefix PATH : ${lib.makeBinPath [ nodejs ]} \
      --set WEBKIT_DISABLE_DMABUF_RENDERER 0
  '';

  meta = {
    description = "Real-time global intelligence dashboard";
    homepage = "https://github.com/koala73/worldmonitor";
    license = lib.licenses.agpl3Only;
    platforms = [ "x86_64-linux" ];
    mainProgram = "world-monitor";
  };
})
